---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ASUS.
--- DateTime: 2026/2/12 12:21
---
-- 1. 参数列表
local voucherId = ARGV[1]
local userId = ARGV[2]

-- 2. 数据key
-- 库存Key
local stockKey = 'seckill:stock:' .. voucherId
-- 订单Key (使用Set集合存储已购买的用户ID)
local orderKey = 'seckill:order:' .. voucherId

-- 3. 脚本业务
-- 3.1. 判断库存是否充足
if (tonumber(redis.call('get', stockKey) or 0) <= 0) then
    return 1 -- 库存不足
end

-- 3.2. 判断用户是否下单
if (redis.call('sismember', orderKey, userId) == 1) then
    return 2 -- 重复下单
end

-- 3.3. 扣减库存
redis.call('incrby', stockKey, -1)

-- 3.4. 下单 (保存用户到集合)
redis.call('sadd', orderKey, userId)

return 0 -- 成功