#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate large MySQL seed SQL for performance testing (ingredients 5000+, merchants, users, products, links).
Run from repo root:
  python3 scripts/generate_perf_seed.py --out docker/mysql/init/seed_performance_data.sql

More rows (e.g. 12k ingredients, 5k products):
  python3 scripts/generate_perf_seed.py --ingredients 12000 --products 5000 --merchants 800 --users 3000 --out docker/mysql/init/seed_performance_data.sql

Import:
  cat docker/mysql/init/seed_performance_data.sql | docker exec -i intellrecipe-mysql mysql -uroot -pPASS intell_recipe
"""
from __future__ import annotations

import argparse
import random
from pathlib import Path

# Fixed ranges — avoid collision with seed_demo_data.sql (merchants 501–503, ingredients 60001+, products 70001+)
MERCHANT_ID_START = 10_000
INGREDIENT_ID_START = 200_001
PRODUCT_ID_START = 2_100_001
USER_PHONE_START = 188_0001_0000  # 11-digit mobiles
PI_LINK_ID_START = 50_000_001

PREFIXES = (
    "冷鲜", "有机", "净菜", "去皮", "免洗", "速冻", "当日", "精选", "进口", "本地",
    "A级", "特级", "小份", "大份", "组合装", "切段", "丝片", "丁块", "轻食", "火锅",
    "煲汤", "凉拌", "快炒", "炖煮", "蒸制", "香煎", "卤味", "腌制", "开袋即食", "锁鲜",
)

CORE_INGREDIENTS = (
    "鸡蛋", "鸭蛋", "鹌鹑蛋", "西红柿", "圣女果", "土豆", "红薯", "紫薯", "青椒", "尖椒",
    "彩椒", "大蒜", "独头蒜", "生姜", "沙姜", "小葱", "大葱", "洋葱", "红葱头", "五花肉",
    "梅花肉", "里脊肉", "后腿肉", "猪蹄", "排骨", "筒骨", "牛腩", "牛腱", "肥牛卷", "羊肉片",
    "羊排", "鸡翅中", "鸡翅根", "鸡爪", "鸡胸", "鸡腿", "整鸡", "老鸭", "鸽子", "鹌鹑",
    "草鱼", "鲈鱼", "黑鱼", "带鱼", "黄鱼", "基围虾", "对虾", "青口贝", "花蛤", "蛏子",
    "扇贝", "生蚝", "鱿鱼", "墨鱼", "八爪鱼", "北豆腐", "嫩豆腐", "内酯豆腐", "豆皮", "腐竹",
    "油豆腐", "千张", "素鸡", "鲜香菇", "干香菇", "杏鲍菇", "平菇", "金针菇", "蟹味菇", "白玉菇",
    "木耳", "银耳", "竹荪", "羊肚菌", "虫草花", "海带", "紫菜", "裙带菜", "海蜇", "龙须菜",
    "菠菜", "生菜", "油麦菜", "小白菜", "大白菜", "娃娃菜", "芹菜", "西芹", "香菜", "茼蒿",
    "空心菜", "苋菜", "芥蓝", "菜心", "西兰花", "花椰菜", "莲藕", "菱角", "荸荠", "芦笋",
    "竹笋", "玉米", "豌豆", "蚕豆", "毛豆", "四季豆", "豇豆", "扁豆", "黄瓜", "冬瓜",
    "南瓜", "丝瓜", "苦瓜", "佛手瓜", "茄子", "胡萝卜", "白萝卜", "青萝卜", "樱桃萝卜", "心里美",
    "芋头", "山药", "魔芋", "莴笋", "韭菜", "韭黄", "蒜苗", "蒜苔", "小葱", "茴香苗",
    "五常大米", "泰国香米", "糯米", "黑米", "糙米", "小米", "燕麦", "藜麦", "红豆", "绿豆",
    "黑豆", "芸豆", "花豆", "鹰嘴豆", "莲子", "百合", "红枣", "桂圆", "枸杞", "核桃",
    "花生", "芝麻", "葵花籽", "生抽", "老抽", "蚝油", "鱼露", "蒸鱼豉油", "料酒", "米醋",
    "陈醋", "香醋", "白醋", "冰糖", "白砂糖", "红糖", "麦芽糖", "蜂蜜", "食盐", "海盐",
    "黑胡椒", "白胡椒", "花椒", "藤椒", "孜然", "辣椒粉", "十三香", "五香粉", "八角", "桂皮",
    "香叶", "草果", "白芷", "豆蔻", "小茴香", "干辣椒", "小米辣", "泡椒", "酸菜", "榨菜",
    "雪菜", "梅干菜", "笋干", "黄花菜", "干豆角", "红薯粉条", "土豆粉条", "粉丝", "宽粉", "年糕",
    "汤圆", "馄饨皮", "饺子皮", "手擀面", "挂面", "刀削面", "意大利面", "乌冬面", "拉面", "米粉",
    "河粉", "凉皮", "面筋", "烤麸", "油面筋", "午餐肉", "培根", "香肠", "腊肠", "火腿",
    "肉松", "蟹棒", "鱼豆腐", "撒尿牛丸", "虾滑", "墨鱼丸", "黄油", "淡奶油", "奶酪", "酸奶",
    "牛奶", "豆浆", "豆腐脑", "抹茶粉", "可可粉", "椰浆", "淡奶油", "吉利丁", "酵母", "小苏打",
    "泡打粉", "玉米淀粉", "木薯淀粉", "澄粉", "高筋面粉", "中筋面粉", "低筋面粉", "全麦粉", "荞麦面", "莜面",
)

NUTRITION = (
    "16千卡/100g", "18千卡/100g", "22千卡/100g", "24千卡/100g", "32千卡/100g", "41千卡/100g",
    "46千卡/100g", "52千卡/100g", "63千卡/100g", "77千卡/100g", "81千卡/100g", "87千卡/100g",
    "112千卡/100g", "126千卡/100g", "144千卡/100g", "194千卡/100g", "250千卡/100g", "263千卡/100g",
    "298千卡/100g", "324千卡/100g", "346千卡/100g", "395千卡/100g", "405千卡/100g", "717千卡/100g",
    "884千卡/100g", "约210千卡/100g", "约180千卡/100g", "约95千卡/100g", "约130千卡/100g",
)

CITIES = (
    "北京朝阳", "上海浦东", "广州天河", "深圳南山", "杭州西湖", "成都锦江", "武汉江汉",
    "西安雁塔", "南京鼓楼", "重庆渝中", "苏州工业园", "天津和平", "长沙岳麓", "郑州金水",
)


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "''")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=None, help="Output SQL path (default: stdout)")
    ap.add_argument("--ingredients", type=int, default=5200, help="Number of ingredient rows")
    ap.add_argument("--merchants", type=int, default=500, help="Number of performance merchants")
    ap.add_argument("--products", type=int, default=2500, help="Number of products")
    ap.add_argument("--users", type=int, default=2000, help="Number of users (unique phone)")
    ap.add_argument("--links-per-product", type=int, default=3, help="product_ingredient rows per product")
    ap.add_argument("--batch", type=int, default=150, help="Rows per INSERT statement")
    ap.add_argument("--seed", type=int, default=42, help="RNG seed for reproducible prices")
    args = ap.parse_args()
    rnd = random.Random(args.seed)

    last_phone = USER_PHONE_START + args.users - 1
    max_link_id = PI_LINK_ID_START + args.products * args.links_per_product

    lines: list[str] = [
        "-- AUTO-GENERATED by scripts/generate_perf_seed.py — performance / pagination test data.",
        "-- ID ranges do not overlap seed_demo_data.sql (501–503 merchants, 60001+ demo ingredients, etc.).",
        "USE intell_recipe;",
        "SET NAMES utf8mb4;",
        "",
        "-- Clean previous perf seed (same ID ranges)",
        f"DELETE FROM `product_ingredient` WHERE `id` BETWEEN {PI_LINK_ID_START} AND {max_link_id};",
        f"DELETE FROM `product` WHERE `id` BETWEEN {PRODUCT_ID_START + 1} AND {PRODUCT_ID_START + args.products};",
        f"DELETE FROM `ingredient` WHERE `id` BETWEEN {INGREDIENT_ID_START + 1} AND {INGREDIENT_ID_START + args.ingredients};",
        f"DELETE FROM `merchant` WHERE `id` BETWEEN {MERCHANT_ID_START + 1} AND {MERCHANT_ID_START + args.merchants};",
        f"DELETE FROM `user` WHERE `phone` BETWEEN '{USER_PHONE_START}' AND '{last_phone}';",
        "",
    ]

    # merchants
    m_rows = []
    for i in range(1, args.merchants + 1):
        mid = MERCHANT_ID_START + i
        city = CITIES[(i - 1) % len(CITIES)]
        score = round(3.5 + rnd.random() * 1.4, 1)
        name = f"压测鲜生第{i:04d}号店"
        addr = f"{city}区压测路{(i % 200) + 1}号"
        phone = f"0571-{8000000 + (mid % 8999999):07d}"
        img = f"https://picsum.photos/seed/m{mid}/400/300"
        desc = esc(f"自动化压测商家，编号{i}，主营生鲜与半成品。")
        op = f"{6 + (i % 3):02d}:00-{20 + (i % 4):02d}:30"
        m_rows.append(
            f"({mid},'{esc(name)}','{esc(addr)}','{phone}','{img}',{score},'{desc}','{op}',0)"
        )
    for j in range(0, len(m_rows), args.batch):
        chunk = m_rows[j : j + args.batch]
        lines.append(
            "INSERT INTO `merchant` (`id`,`name`,`address`,`phone`,`image`,`score`,`description`,`open_time`,`deleted`) VALUES\n"
            + ",\n".join(chunk)
            + ";"
        )
    lines.append("")

    # users (phones 18800010000 ..) — 11 digits
    u_rows = []
    for i in range(args.users):
        phone = str(USER_PHONE_START + i)
        nick = esc(f"压测用户_{i:05d}")
        avatar = f"https://picsum.photos/seed/u{USER_PHONE_START + i}/200/200"
        u_rows.append(f"('{phone}','{nick}',NULL,'{avatar}',0,0)")
    for j in range(0, len(u_rows), args.batch):
        chunk = u_rows[j : j + args.batch]
        lines.append(
            "INSERT IGNORE INTO `user` (`phone`,`nickname`,`password`,`avatar`,`status`,`deleted`) VALUES\n"
            + ",\n".join(chunk)
            + ";"
        )
    lines.append("")

    # ingredients
    ing_rows = []
    for i in range(1, args.ingredients + 1):
        iid = INGREDIENT_ID_START + i
        pre = PREFIXES[(i * 7) % len(PREFIXES)]
        core = CORE_INGREDIENTS[(i * 13) % len(CORE_INGREDIENTS)]
        name = esc(f"{pre}{core}·批次{i:05d}")
        img = f"https://picsum.photos/seed/ing{iid}/200/200"
        desc = esc(f"性能测试食材库：编号{i}，用于关键词检索、分页、去重与列表接口压测。")
        nut = NUTRITION[(i * 3) % len(NUTRITION)]
        ing_rows.append(f"({iid},'{name}','{img}','{desc}','{esc(nut)}',0)")
    for j in range(0, len(ing_rows), args.batch):
        chunk = ing_rows[j : j + args.batch]
        lines.append(
            "INSERT INTO `ingredient` (`id`,`name`,`image`,`description`,`nutrition_value`,`deleted`) VALUES\n"
            + ",\n".join(chunk)
            + ";"
        )
    lines.append("")

    # products
    p_rows = []
    for i in range(1, args.products + 1):
        pid = PRODUCT_ID_START + i
        mid = MERCHANT_ID_START + 1 + (i % args.merchants)
        price = round(5 + rnd.random() * 195, 2)
        w = round(200 + rnd.random() * 4800, 2)
        unit = ("g", "ml", "份")[(i + mid) % 3]
        pname = esc(f"压测商品_{i:05d}_{CORE_INGREDIENTS[i % len(CORE_INGREDIENTS)]}套餐")
        pimg = f"https://picsum.photos/seed/p{pid}/400/300"
        pdesc = esc(f"关联商家ID {mid}，用于商品列表、筛选与详情接口压测。")
        p_rows.append(f"({pid},{mid},'{pname}',{price},'{pimg}','{pdesc}',{w},'{unit}',1,0)")
    for j in range(0, len(p_rows), args.batch):
        chunk = p_rows[j : j + args.batch]
        lines.append(
            "INSERT INTO `product` (`id`,`merchant_id`,`name`,`price`,`image`,`description`,`weight`,`unit`,`status`,`deleted`) VALUES\n"
            + ",\n".join(chunk)
            + ";"
        )
    lines.append("")

    # product_ingredient — deterministic links for stable tests
    pi_rows = []
    link_id = PI_LINK_ID_START
    for i in range(1, args.products + 1):
        pid = PRODUCT_ID_START + i
        for k in range(args.links_per_product):
            off = (i * 17 + k * 131) % args.ingredients
            iid = INGREDIENT_ID_START + 1 + off
            pi_rows.append(f"({link_id},{pid},{iid},0)")
            link_id += 1
    for j in range(0, len(pi_rows), args.batch):
        chunk = pi_rows[j : j + args.batch]
        lines.append(
            "INSERT INTO `product_ingredient` (`id`,`product_id`,`ingredient_id`,`deleted`) VALUES\n"
            + ",\n".join(chunk)
            + ";"
        )

    lines.append("")
    lines.append(
        "SELECT 'perf seed done' AS msg,"
        f" (SELECT COUNT(*) FROM ingredient WHERE id BETWEEN {INGREDIENT_ID_START + 1} AND {INGREDIENT_ID_START + args.ingredients}) AS perf_ingredients,"
        f" (SELECT COUNT(*) FROM product WHERE id BETWEEN {PRODUCT_ID_START + 1} AND {PRODUCT_ID_START + args.products}) AS perf_products;"
    )

    text = "\n".join(lines) + "\n"
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text, encoding="utf-8")
        print(f"Wrote {args.out} ({len(text) // 1024} KiB)", file=__import__("sys").stderr)
    else:
        print(text, end="")


if __name__ == "__main__":
    main()
